#!/usr/bin/env bash
set -euo pipefail

DEPLOY_FILE="deploy.sh"
BOOTSTRAP_CONFIG_FILE="hosts/oci-melb-1/bootstrap-config.nix"
DO_BOOTSTRAP_CONFIG_FILE="hosts/do-admin-1/bootstrap-config.nix"
HOST_FILE="hosts/oci-melb-1/default.nix"
DO_HOST_FILE="hosts/do-admin-1/default.nix"
DISKO_FILE="modules/storage/disko-root.nix"
DO_DISKO_FILE="modules/storage/disko-single-disk.nix"
JUSTFILE="justfile"
OCI_PROVIDER_FILE="modules/providers/oci/default.nix"
DO_PROVIDER_FILE="modules/providers/digitalocean/default.nix"

rg --fixed-strings --quiet 'nix run github:nix-community/nixos-anywhere --' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- 'BOOTSTRAP_CONFIG="${SCRIPT_DIR}/hosts/oci-melb-1/bootstrap-config.nix"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- '--host-config <path>' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- '--bootstrap-key-mode <live|injected>' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- '--host-public-key <ssh-ed25519...>' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- '--host-age-recipient <age1...>' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- 'TARGET_HOST="$(nix eval --raw --file "$BOOTSTRAP_CONFIG" hostName)"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- 'BOOTSTRAP_USER="$(nix eval --raw --file "$BOOTSTRAP_CONFIG" bootstrapUser)"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- 'FLAKE_TARGET="$(nix eval --raw --file "$BOOTSTRAP_CONFIG" flake)"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- 'HARDWARE_CONFIG_GENERATOR="$(eval_bootstrap_attr_with_fallback hardwareConfigGenerator "nixos-generate-config")"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- 'HARDWARE_CONFIG_PATH="$(eval_bootstrap_attr_with_fallback hardwareConfigPath "hosts/oci-melb-1/hardware-configuration.nix")"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- 'DERIVED_HOST_AGE_RECIPIENT="$(derive_host_age_recipient "$BOOTSTRAP_KEY_MODE" "$TARGET_HOST" "22" "$BOOTSTRAP_HOST_PUBLIC_KEY" "$BOOTSTRAP_HOST_AGE_RECIPIENT")"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- '--flake "$FLAKE_TARGET"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- '--build-on remote' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- '--target-host "${BOOTSTRAP_USER}@${TARGET_HOST}"' "$DEPLOY_FILE"
rg --fixed-strings --quiet -- '--generate-hardware-config "$HARDWARE_CONFIG_GENERATOR" "$HARDWARE_CONFIG_PATH"' "$DEPLOY_FILE"
! rg --fixed-strings --quiet 'root@${TARGET_HOST}' "$DEPLOY_FILE"

rg --fixed-strings --quiet 'bootstrapUser = "ubuntu";' "$BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'bootstrapDisk = "/dev/sda";' "$BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'mediaDisk = "/dev/sdb";' "$BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'rootPartitionSize = "20G";' "$BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'flake = "path:.#oci-melb-1";' "$BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'hardwareConfigGenerator = "nixos-generate-config";' "$BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'hardwareConfigPath = "hosts/oci-melb-1/hardware-configuration.nix";' "$BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'disko.devices.disk.main.device = "/dev/sda";' "$HOST_FILE"
rg --fixed-strings --quiet 'disko.devices.disk.media.device = "/dev/sdb";' "$HOST_FILE"
rg --fixed-strings --quiet 'disko.devices.disk.main.device = "/dev/vda";' "$DO_HOST_FILE"
rg --fixed-strings --quiet 'boot.loader.grub.devices = [ "/dev/sda" ];' "$OCI_PROVIDER_FILE"

rg --fixed-strings --quiet 'hostName = "do-admin-1";' "$DO_BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'bootstrapUser = "root";' "$DO_BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'bootstrapDisk = "/dev/vda";' "$DO_BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'flake = "path:.#do-admin-1";' "$DO_BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet 'hardwareConfigPath = "hosts/do-admin-1/hardware-configuration.nix";' "$DO_BOOTSTRAP_CONFIG_FILE"
rg --fixed-strings --quiet '/virtualisation/digital-ocean-config.nix' "$DO_PROVIDER_FILE"
rg --fixed-strings --quiet 'datasource_list = [' "$DO_PROVIDER_FILE"
rg --fixed-strings --quiet '"Digitalocean"' "$DO_PROVIDER_FILE"

rg --fixed-strings --quiet 'bootstrap target=bootstrap_target user=bootstrap_user flake=bootstrap_flake host_config=bootstrap_host_config extra_files=bootstrap_extra_files hardware_config_generator=bootstrap_hardware_config_generator hardware_config_path=bootstrap_hardware_config_path skip_hardware_config=bootstrap_skip_hardware_config key_mode=bootstrap_key_mode host_public_key=bootstrap_host_public_key host_age_recipient=bootstrap_host_age_recipient:' "$JUSTFILE"
rg --fixed-strings --quiet 'hardware_config_generator=bootstrap_hardware_config_generator' "$JUSTFILE"
rg --fixed-strings --quiet 'hardware_config_path=bootstrap_hardware_config_path' "$JUSTFILE"
rg --fixed-strings --quiet 'skip_hardware_config=bootstrap_skip_hardware_config' "$JUSTFILE"
rg --fixed-strings --quiet 'CMD=(./deploy.sh --host-config "{{host_config}}" --target "{{target}}" --bootstrap-user "{{user}}" --flake "{{flake}}" --bootstrap-key-mode "{{key_mode}}")' "$JUSTFILE"
rg --fixed-strings --quiet 'CMD+=(--skip-hardware-config)' "$JUSTFILE"
rg --fixed-strings --quiet 'bootstrap-do target=do_target_host user=do_bootstrap_user:' "$JUSTFILE"
rg --fixed-strings --quiet 'just bootstrap target="{{target}}" user="{{user}}" flake="path:.#do-admin-1" host_config="hosts/do-admin-1/bootstrap-config.nix"' "$JUSTFILE"

rg --fixed-strings --quiet '../../modules/storage/disko-root.nix' "$HOST_FILE"
rg --fixed-strings --quiet '++ lib.optional (builtins.pathExists ./hardware-configuration.nix) ./hardware-configuration.nix;' "$HOST_FILE"
rg --fixed-strings --quiet '../../modules/storage/disko-single-disk.nix' "$DO_HOST_FILE"

rg --fixed-strings --quiet 'mountpoint = "/"' "$DISKO_FILE"
rg --fixed-strings --quiet 'mountpoint = "/srv/data"' "$DISKO_FILE"
rg --fixed-strings --quiet 'mountpoint = "/srv/media"' "$DISKO_FILE"
rg --fixed-strings --quiet '"rootfs"' "$DISKO_FILE"
rg --fixed-strings --quiet '"srv-data"' "$DISKO_FILE"
rg --fixed-strings --quiet '"srv-media"' "$DISKO_FILE"
rg --fixed-strings --quiet 'mountpoint = "/"' "$DO_DISKO_FILE"
