sops:
    age:
        - recipient: age1w5asfm5rfncy4yvslj3az78kvn7hkrzq4vy0mzexf36w64a7e3nqamw3fp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaDZPektFTlRWUkFsK0Qy
            cmFHSjVnaW1weUcrbGlON1BnMjBTRVJmZmhnClNoVzhhZlJZM09wNTFGa2oxb2tY
            Vks1V0xoNUgycEZCbTJjUE5NNFovSHcKLS0tIFJqVTUwKytpcFZlYVFDaEdiMkYw
            aS81WCtVYWNBY1VKeGJKQ1hWUCs2RzgKHhEcuFG12YrUiqqH1Lq6bikyHIw2bnKt
            aHT1K2qxZK4vsOGNlmKGUkFhGMenMJsOYaAySNO5S6S6CRAz15Iakw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lg45rhdn6mp856f97sdwxu7rpzyyz7edqwnldnpj67r6curnkqws7nn42a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dDlVVGJiSExCR00wTVRa
            TnpuUGIyeDQzancxTUN6emVwSWJRalYzakU0CnZ3V2Jxa1YxWWZtZDRTQ1lrb1d2
            Q0hCNGxIVWdBMGxyczYvRUVTdHU3ZTgKLS0tIDBWT3lPOVlNbHdpL0lTb3JwMVE4
            ZWV4SHphSGpPVkV2OGJhWUQ4MnpuWjAKct8U9/qq/SEJJpIsa4tzxbkE/zAIi6jX
            gJw75bZHsx9rpdGDYfz4mA3YUZ7QxHXd4kAAZh3ce8JiC1oJ5VRilA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a2masnj7tmwjl9azt75kh387lvwwz9vqfhqr0emghdcvu7x9jd9q4wv4aq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVk9TL0hxNU9DMHBvakQr
            SUFDb3J1bzRWeU5rOVhHQWlHeVpxM1dCY1U0CmVHV3hnS0F0RU45Nmw4MXpXcXZW
            REFPZ0JPVXZackhvUXVXYUQ5dWR4d1UKLS0tIE5wQ053MlFqWW93RHQ5VVZrRXdI
            TkYxb1Flc1U2N20zN2ZwK055YW1sWmcK4adHvnvL6wZdXYcqKUxWznLdxwsw6AyL
            /z9RTRQZlKM6K/zgNPhkehPTqlEOCnMwz2qk/+4PkWB6/ixp8q74Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T22:21:24Z"
    mac: ENC[AES256_GCM,data:CCpkuRtL2F1/4lMAB930o5CFP/7ZO3A6RzD5zedhFi08kPP3BBUm0/K0wC5Qe+iTh38Et086EC18TBmFXYm5WAoo3uxoeJUCPLqtBbEnKxDEj+mb/hBzfqM0VNRDBcvmOnpgMD+OjWaa+TQ1SwRzV5fi5r26KvtwEJI+H2nQshM=,iv:3FJCoh34FX7MxreY7cE3nIDtGpQJHTOv9AP6bS3KFtI=,tag:DeAuI++Erdf1fKfK31wH7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
