cloudflare:
    dns_api_token: ENC[AES256_GCM,data:ptwQKAHyijLVYhk4gfam5Mp53aQWNXFw2nugN/WO5X5OHZAoeYuLsAYF37szliN1gpgB2iA=,iv:pS/uNONiuU61vMQllsSKobwG5pfHIMgXEBkB5SqxPaw=,tag:HurRxzDN+H+oZ5zL9xiw8g==,type:str]
sops:
    age:
        - recipient: age1w5asfm5rfncy4yvslj3az78kvn7hkrzq4vy0mzexf36w64a7e3nqamw3fp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM1lQdmFKYW5pN1BXdEdD
            K09uN210d21yd1QyQ1BpRmQyVTMvWGhtMG1RCllIbzhOQmk3dWdyVVdydDYrcXc1
            VDF1NEFLYUxqTkF1aEY1MDZHRXRQUWcKLS0tIGFZeVQ2aERzTUlzT25CZ0FyR201
            ZTRvTURVNGRiZjRZcGIvWXhpNkEraXcKeA+jmPg9VX72YnYMYz63jOtjCWnFT+Iv
            IZfWuG6WYPMt28MQs4qyEMvl4Q4Kowsd3yek719uDmjIlC6XewkD0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lg45rhdn6mp856f97sdwxu7rpzyyz7edqwnldnpj67r6curnkqws7nn42a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N0l4eDR6M2RyOWJ2VkFO
            ZHd2aXZKTGpqb0JwU2kvT3BNZHgwaGluc0YwCndKemxaZ1F3N3FVS1luT3VOYUdq
            QnkwOGN4SUZwZzFTaUtKVE0wcU5QcE0KLS0tIFVneDMwWFNRYjlTYXBLaG1iQmtI
            RVJPL2tCenptR2F1UFl0czRVdjUzOUEKnzuurfycBfoKvG2ILLnyELxwesAKkoAm
            wQ1njbQrfo/PFZR64ftKB8EZjmUeBP+QgfRd/eCizBfrA2Qnqd6bZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a2masnj7tmwjl9azt75kh387lvwwz9vqfhqr0emghdcvu7x9jd9q4wv4aq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OS9nZVRxL3czQmpEWCsv
            d0JkSTEyNTFBRVVWejNRQ2hvU3V5RFVjTTJrCmMrdVZRMlVCd2pDTkUxM2JkTWJr
            cmpEYVAwbGIyQ3JuYkFYZS9mZ3pUSVUKLS0tIGx0bVpCWkxaOU5pdTJvbXVySjVq
            VHlkVldaL0ViOGVxd2g1ZmMxMHFtVDQKNtNSjY1ij+HXhirsjr9HKieudfxJglzR
            XC2fgtYTYAMo3REfo6iQwPOz090EryRX7Zqlqh6M6v0XVpJxshDpTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T11:01:27Z"
    mac: ENC[AES256_GCM,data:l0nRIutWK5g0WPYaX4Ocl4I3uKs0yvYNfXCkbaU1avEiTPEIJdmzNifz8V0ZtR2s3O7/nSDa9F7vBi6cpSRtD7kCSGR4Vm0uytw7NioTJYPqofaRKYaMP6c9Jl83ttM0f05wYELompEFvKNjZwL5RUrJfo4iWa1ACAvLFn5Vcqs=,iv:5iOze4vGs90lFYisP7gHLKpt6wxNgF9pHn0Q7QwnlUQ=,tag:TFlwQJzY+hspqj6AP1SO1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2

